default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_api_practice_development

test:
  <<: *default
  database: rails_api_practice_test

production:
  <<: *default
  database: rails_api_practice_production
  username: rails_api_practice
  password: <%= ENV['RAILS_API_PRACTICE_DATABASE_PASSWORD'] %>
